export interface Book {
  id: number;
  title: string;
  author: string;
  price: number;
  originalPrice: number;
  condition: string;
  image: string;
  category: string;
  description: string;
  pages: number;
  publisher: string;
  publishedDate: string;
  isbn: string;
  seller: string;
  sellerEmail: string;
  rating: number;
  reviews: number;
  inStock: boolean;
}

export const initialBooks: Book[] = [
  {
    id: 1,
    title: "NCERT Mathematics Class 10",
    author: "NCERT",
    price: 299,
    originalPrice: 450,
    condition: "Good",
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=600&fit=crop",
    category: "ncert",
    description: "Official NCERT Mathematics textbook for Class 10. Recommended by CBSE board for building solid mathematical fundamentals. Includes chapters on Real Numbers, Polynomials, Triangles, Trigonometry, and Statistics.",
    pages: 350,
    publisher: "National Council of Educational Research and Training",
    publishedDate: "2023",
    isbn: "978-81-7450-482-1",
    seller: "Rahul Kumar",
    sellerEmail: "rahul.kumar@example.com",
    rating: 4.6,
    reviews: 84,
    inStock: true,
  },
  {
    id: 2,
    title: "RS Aggarwal Quantitative Aptitude",
    author: "R.S. Aggarwal",
    price: 449,
    originalPrice: 699,
    condition: "Excellent",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400&h=600&fit=crop",
    category: "competitive",
    description: "An indispensable guide for students preparing for competitive examinations. Covers a wide range of quantitative questions, short-cut formulas, and solved examples for Bank PO, SSC, MBA, and other entrance exams.",
    pages: 960,
    publisher: "S. Chand Publishing",
    publishedDate: "2022",
    isbn: "978-93-5501-123-2",
    seller: "Priyanka Roy",
    sellerEmail: "priyanka.roy@example.com",
    rating: 4.8,
    reviews: 142,
    inStock: true,
  },
  {
    id: 3,
    title: "Lucent's General Knowledge",
    author: "Lucent Publication",
    price: 199,
    originalPrice: 280,
    condition: "Fair",
    image: "https://images.unsplash.com/photo-1513001900722-370f803f498d?w=400&h=600&fit=crop",
    category: "government",
    description: "The ultimate handbook for general knowledge. Covers History, Geography, Indian Polity, Economy, and General Science, designed specifically for students appearing for competitive government job exams.",
    pages: 410,
    publisher: "Lucent Publications",
    publishedDate: "2023",
    isbn: "978-81-9331-563-5",
    seller: "Amit Singh",
    sellerEmail: "amit.singh@example.com",
    rating: 4.5,
    reviews: 96,
    inStock: true,
  },
  {
    id: 4,
    title: "RD Sharma Class 11",
    author: "R.D. Sharma",
    price: 599,
    originalPrice: 850,
    condition: "Excellent",
    image: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&h=600&fit=crop",
    category: "ncert",
    description: "A comprehensive reference book for CBSE Class 11 Mathematics by R.D. Sharma. Contains detailed explanations, step-by-step solutions, and numerous practice problems to clear all concepts for both board exams and JEE preparations.",
    pages: 1120,
    publisher: "Dhanpat Rai Publications",
    publishedDate: "2022",
    isbn: "978-93-8968-356-0",
    seller: "Vikram Shah",
    sellerEmail: "vikram.shah@example.com",
    rating: 4.7,
    reviews: 65,
    inStock: true,
  },
  {
    id: 5,
    title: "Arihant General Studies Paper 2",
    author: "Arihant Experts",
    price: 379,
    originalPrice: 550,
    condition: "Good",
    image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400&h=600&fit=crop",
    category: "government",
    description: "Arihant General Studies Manual for Civil Services (CSAT) Paper 2. Offers thorough coverage of Comprehension, Interpersonal Skills, Logical Reasoning, Decision Making, and Basic Numeracy.",
    pages: 720,
    publisher: "Arihant Publications",
    publishedDate: "2021",
    isbn: "978-93-2529-214-5",
    seller: "Divya Pathak",
    sellerEmail: "divya.pathak@example.com",
    rating: 4.4,
    reviews: 38,
    inStock: true,
  },
  {
    id: 6,
    title: "NCERT Science Class 9",
    author: "NCERT",
    price: 249,
    originalPrice: 380,
    condition: "Good",
    image: "https://images.unsplash.com/photo-1532187640605-a359af7ef7db?w=400&h=600&fit=crop",
    category: "ncert",
    description: "Official NCERT Science textbook for Class 9. Core textbook prescribed by CBSE covering fundamental concepts of Physics, Chemistry, and Biology, including Matter, Cells, Motion, Forces, and Diversity.",
    pages: 280,
    publisher: "National Council of Educational Research and Training",
    publishedDate: "2023",
    isbn: "978-81-7450-512-5",
    seller: "Karan Johar",
    sellerEmail: "karan.johar@example.com",
    rating: 4.6,
    reviews: 47,
    inStock: true,
  },
  {
    id: 7,
    title: "HC Verma Concepts of Physics",
    author: "H.C. Verma",
    price: 499,
    originalPrice: 750,
    condition: "Excellent",
    image: "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=400&h=600&fit=crop",
    category: "reference",
    description: "Concepts of Physics (Volume 1) by Dr. H.C. Verma. An essential textbook for JEE aspirants and Class 11/12 students. Connects theoretical concepts with practical problems, enabling deep understanding.",
    pages: 462,
    publisher: "Bharati Bhawan Publishers",
    publishedDate: "2022",
    isbn: "978-81-7709-179-3",
    seller: "Rohan Das",
    sellerEmail: "rohan.das@example.com",
    rating: 4.9,
    reviews: 310,
    inStock: true,
  },
  {
    id: 8,
    title: "Disha Chapterwise MCQ",
    author: "Disha Experts",
    price: 329,
    originalPrice: 499,
    condition: "Good",
    image: "https://images.unsplash.com/photo-1588072432836-e10032774350?w=400&h=600&fit=crop",
    category: "competitive",
    description: "Disha's 10,000+ Objective General Studies MCQs. Ideal reference book for practicing chapterwise and topicwise multiple choice questions for UPSC, State PSC, SSC, and Banking exams.",
    pages: 580,
    publisher: "Disha Publication",
    publishedDate: "2023",
    isbn: "978-93-9071-120-8",
    seller: "Suman Kalyan",
    sellerEmail: "suman.kalyan@example.com",
    rating: 4.3,
    reviews: 52,
    inStock: true,
  },
  {
    id: 9,
    title: "NCERT Physics Class 12",
    author: "NCERT",
    price: 349,
    originalPrice: 520,
    condition: "Good",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&h=600&fit=crop",
    category: "ncert",
    description: "Official NCERT Physics Part 1 & Part 2 textbook for Class 12. Covers Electrostatics, Magnetism, Electromagnetic Induction, Optics, and Modern Physics, vital for school boards and entrance tests.",
    pages: 540,
    publisher: "National Council of Educational Research and Training",
    publishedDate: "2023",
    isbn: "978-81-7450-652-8",
    seller: "Vikram Shah",
    sellerEmail: "vikram.shah@example.com",
    rating: 4.5,
    reviews: 73,
    inStock: true,
  },
  {
    id: 10,
    title: "Kiran's SSC Mathematics",
    author: "Kiran Publication",
    price: 279,
    originalPrice: 420,
    condition: "Excellent",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=600&fit=crop",
    category: "government",
    description: "Kiran's SSC Mathematics Chapterwise & Typewise Solved Papers (1999-Present). Contains detailed explanations for all questions, very useful for SSC CGL, CHSL, MTS, and GD Constable aspirants.",
    pages: 890,
    publisher: "Kiran Institute of Career Excellence",
    publishedDate: "2023",
    isbn: "978-93-5715-189-0",
    seller: "Amit Singh",
    sellerEmail: "amit.singh@example.com",
    rating: 4.7,
    reviews: 119,
    inStock: true,
  },
  {
    id: 11,
    title: "Pradeep's Chemistry Class 11",
    author: "Pradeep Publications",
    price: 429,
    originalPrice: 650,
    condition: "Fair",
    image: "https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=400&h=600&fit=crop",
    category: "reference",
    description: "Pradeep's New Course Chemistry for Class 11. Designed to assist students in mastering Chemistry concepts. Features high-quality diagrams, tables, questions from standard competitive exams, and conceptual problems.",
    pages: 820,
    publisher: "Pradeep Publications",
    publishedDate: "2022",
    isbn: "978-81-9304-453-2",
    seller: "Deepak Rawat",
    sellerEmail: "deepak.rawat@example.com",
    rating: 4.4,
    reviews: 29,
    inStock: true,
  },
  {
    id: 12,
    title: "Fast Track Objective Arithmetic",
    author: "Rajesh Verma",
    price: 399,
    originalPrice: 599,
    condition: "Good",
    image: "https://images.unsplash.com/photo-1448697138198-9fa6d0dbd44f?w=400&h=600&fit=crop",
    category: "competitive",
    description: "Arihant's Fast Track Objective Arithmetic by Rajesh Verma. The book provides simple and shortcut methods to solve arithmetic problems, catering to SSC, Banking, Railway, CSAT, and other exams.",
    pages: 512,
    publisher: "Arihant Publications",
    publishedDate: "2022",
    isbn: "978-93-2529-268-8",
    seller: "Priyanka Roy",
    sellerEmail: "priyanka.roy@example.com",
    rating: 4.6,
    reviews: 67,
    inStock: true,
  },
];
